In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataset.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,NaN,Yes,No,NaN,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,NaN,No,No,34.0,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,NaN,No,No,2.0,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,NaN,No,No,45.0,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,NaN,No,No,2.0,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

## 1- missing values 
- fill
    - mean
    - median 
    - mode == most frequent 
    - constant 0 - 1
    - min
    - max
    - mean of each group --> clustering
    - previous or next value --> time series dataset only
    - random value
    - prediction/classification
- drop if missing values less than ....

In [3]:
df.isna().sum()

customerID            0
gender                0
SeniorCitizen        43
Partner               0
Dependents            0
tenure              147
PhoneService          0
MultipleLines         0
InternetService       0
OnlineSecurity        0
OnlineBackup          0
DeviceProtection      0
TechSupport           0
StreamingTV           0
StreamingMovies       0
Contract              0
PaperlessBilling      0
PaymentMethod         0
MonthlyCharges        0
TotalCharges          0
Churn                 0
dtype: int64

In [7]:
(df.isna().sum()/df.shape[0])*100

customerID          0.000000
gender              0.000000
SeniorCitizen       0.610535
Partner             0.000000
Dependents          0.000000
tenure              2.087179
PhoneService        0.000000
MultipleLines       0.000000
InternetService     0.000000
OnlineSecurity      0.000000
OnlineBackup        0.000000
DeviceProtection    0.000000
TechSupport         0.000000
StreamingTV         0.000000
StreamingMovies     0.000000
Contract            0.000000
PaperlessBilling    0.000000
PaymentMethod       0.000000
MonthlyCharges      0.000000
TotalCharges        0.000000
Churn               0.000000
dtype: float64

In [5]:
df.dropna(subset=['tenure'])

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
1,5575-GNVDE,Male,NaN,No,No,34.0,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,NaN,No,No,2.0,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,NaN,No,No,45.0,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,NaN,No,No,2.0,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,NaN,No,No,8.0,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0.0,Yes,Yes,24.0,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,2234-XADUH,Female,0.0,Yes,Yes,72.0,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,4801-JZAZL,Female,0.0,Yes,Yes,11.0,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1.0,Yes,No,4.0,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,3186-AJIEK,Male,0.0,No,No,66.0,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [24]:
#df.SeniorCitizen.fillna(0,inplace=True)
#df['SeniorCitizen'] = df.SeniorCitizen.fillna(0)
filler = df.SeniorCitizen.max()
df.SeniorCitizen.fillna(filler)

0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
       ...
7038    0.0
7039    0.0
7040    0.0
7041    1.0
7042    0.0
Name: SeniorCitizen, Length: 7043, dtype: float64

In [22]:
df.SeniorCitizen.mode().values[0]

0.0

In [10]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,NaN,Yes,No,NaN,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,NaN,No,No,34.0,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,NaN,No,No,2.0,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,NaN,No,No,45.0,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,NaN,No,No,2.0,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
#df.to_csv('new.csv')

## 2- Categorical Features

In [27]:
df.gender.replace('Female',0,inplace=True)
df.gender.replace('Male',1,inplace=True)
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,0,NaN,Yes,No,NaN,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,1,NaN,No,No,34.0,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,1,NaN,No,No,2.0,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,1,NaN,No,No,45.0,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,0,NaN,No,No,2.0,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [30]:
#!pip install -U scikit-learn
from sklearn.preprocessing import LabelEncoder

In [31]:
le = LabelEncoder()

In [32]:
le.fit(df.Partner)

LabelEncoder()

In [33]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [34]:
le.transform(df.Partner)

array([1, 0, 0, ..., 1, 1, 0])

In [35]:
le.fit_transform(df.Partner)

array([1, 0, 0, ..., 1, 1, 0])

In [36]:
le.fit_transform(df.MultipleLines)

array([1, 0, 0, ..., 1, 2, 0])

In [37]:
le.classes_

array(['No', 'No phone service', 'Yes'], dtype=object)

In [42]:
partner_le       = LabelEncoder()
dependents_le    = LabelEncoder()
multiplelines_le = LabelEncoder()

df['Partner']       = partner_le.fit_transform(df.Partner)
df['Dependents']    = dependents_le.fit_transform(df.Dependents)
df['MultipleLines'] = multiplelines_le.fit_transform(df.MultipleLines)

In [43]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,0,NaN,1,0,NaN,No,1,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,1,NaN,0,0,34.0,Yes,0,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,1,NaN,0,0,2.0,Yes,0,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,1,NaN,0,0,45.0,No,1,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,0,NaN,0,0,2.0,Yes,0,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [44]:
multiplelines_le.classes_

array(['No', 'No phone service', 'Yes'], dtype=object)

In [45]:
multiplelines_le.inverse_transform([0])

array(['No'], dtype=object)

## 3- Scaling

In [46]:
400/410

0.975609756097561

In [47]:
800/1000

0.8

In [ ]:
(x - x.min())/(x.max()-x.min())

In [48]:
(400 - 0)/ (410 - 0)

0.975609756097561

In [49]:
(df.TotalCharges - df.TotalCharges.min()) / (df.TotalCharges.max() - df.TotalCharges.min())

0       0.001275
1       0.215867
2       0.010310
3       0.210241
4       0.015330
          ...
7038    0.227521
7039    0.847461
7040    0.037809
7041    0.033210
7042    0.787641
Name: TotalCharges, Length: 7043, dtype: float64

In [50]:
(df.MonthlyCharges - df.MonthlyCharges.min()) / (df.MonthlyCharges.max() - df.MonthlyCharges.min())

0       0.115423
1       0.385075
2       0.354229
3       0.239303
4       0.521891
          ...
7038    0.662189
7039    0.845274
7040    0.112935
7041    0.558706
7042    0.869652
Name: MonthlyCharges, Length: 7043, dtype: float64

In [51]:
(df.MonthlyCharges - df.MonthlyCharges.mean()) / (df.MonthlyCharges.std())

0      -1.160241
1      -0.259611
2      -0.362635
3      -0.746482
4       0.197351
          ...
7038    0.665945
7039    1.277443
7040   -1.168549
7041    0.320315
7042    1.358865
Name: MonthlyCharges, Length: 7043, dtype: float64

In [53]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit_transform(df[['TotalCharges','MonthlyCharges']])

array([[-0.99497138, -1.16032292],
       [-0.17387565, -0.25962894],
       [-0.96039939, -0.36266036],
       ...,
       [-0.85518222, -1.1686319 ],
       [-0.87277729,  0.32033821],
       [ 2.01391739,  1.35896134]])

In [ ]:
y = m1x1+m2x2+m3x3+bias